#!/usr/bin/env bash

echo installing required softwares ...

# Yarn
sudo wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo

# Docker
dnf -y install dnf-plugins-core
dnf config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo
dnf config-manager --enable docker-ce-edge
dnf config-manager --disable docker-ce-edge
dnf makecache fast
dnf install docker-ce

systemctl start docker

# Docker Compose
pip install docker-compose

# NPM packages
npm i -q jest -g
npm i -q nodemon -g
npm i -q snyk -g
npm i -q nsp -g

yarn

echo development environment setup complete!